name: ahand_ros2
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - assimp=5.2.5
  - asttokens=3.0.0
  - boost=1.78.0
  - boost-cpp=1.78.0
  - bzip2=1.0.8
  - ca-certificates=2025.11.12
  - comm=0.2.3
  - console_bridge=1.0.2
  - debugpy=1.8.17
  - decorator=5.2.1
  - eigen=3.4.0
  - exceptiongroup=1.3.0
  - executing=2.2.1
  - expat=2.7.3
  - icu=73.2
  - importlib-metadata=8.7.0
  - ipykernel=7.1.0
  - ipython=8.37.0
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.9.1
  - keyutils=1.6.3
  - krb5=1.21.3
  - ld_impl_linux-64=2.44
  - libblas=3.9.0
  - libcblas=3.9.0
  - libedit=3.1.20250104
  - libffi=3.4.6
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libgomp=15.2.0
  - liblapack=3.9.0
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnsl=2.0.1
  - libopenblas=0.3.30
  - libsodium=1.0.20
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.2.13
  - llvm-openmp=21.1.5
  - matplotlib-inline=0.2.1
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - numpy=1.26.4
  - octomap=1.9.8
  - openssl=3.6.0
  - packaging=25.0
  - parso=0.8.5
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pinocchio=2.6.18
  - pip=25.3
  - platformdirs=4.5.0
  - prompt-toolkit=3.0.52
  - psutil=7.1.3
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.2
  - python=3.10.19
  - python-dateutil=2.9.0.post0
  - python_abi=3.10
  - pyzmq=27.1.0
  - qhull=2020.2
  - readline=8.3
  - setuptools=80.9.0
  - six=1.17.0
  - sqlite=3.50.2
  - stack_data=0.6.3
  - tinyxml=2.6.2
  - tk=8.6.15
  - tornado=6.5.2
  - traitlets=5.14.3
  - typing_extensions=4.15.0
  - tzdata=2025b
  - urdfdom=3.1.1
  - urdfdom_headers=1.1.2
  - wcwidth=0.2.14
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - beautifulsoup4==4.14.2
      - certifi==2025.11.12
      - cmeel==0.57.3
      - cmeel-assimp==5.4.3.1
      - cmeel-boost==1.83.0
      - cmeel-console-bridge==1.0.2.3
      - cmeel-octomap==1.10.0
      - cmeel-qhull==8.0.2.1
      - cmeel-tinyxml==2.6.2.3
      - cmeel-urdfdom==3.1.1.1
      - cmeel-zlib==1.3.1
      - colorama==0.4.6
      - cycler==0.12.1
      - eigenpy==3.5.1
      - fonttools==4.60.1
      - hpp-fcl==2.4.4
      - idna==3.11
      - jinja2==3.1.6
      - kiwisolver==1.4.9
      - markupsafe==3.0.3
      - pillow==12.0.0
      - pybind11==3.0.1
      - pyqt5==5.15.11
      - pyqt5-qt5==5.15.17
      - pyqt5-sip==12.17.1
      - pytz==2025.2
      - pyyaml==6.0.3
      - scipy==1.15.3
      - soupsieve==2.8
      - urllib3==2.5.0
      - webencodings==0.5.1
prefix: /home/leo/miniconda3/envs/ahand_ros2
