robot:
  config: './config/thunder/ahand_thumba_par.yaml'
  dynamics:
    link1:
      inertial:
        symb: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
        mass: 0.0446
        CoM_x: 0.0
        CoM_y: 0.0
        CoM_z: 0.0
        Ixx: 5.44e-05
        Ixy: 4.0e-07
        Ixz: -1.12e-07
        Iyy: 9.19e-06
        Iyz: 1.07e-05
        Izz: 4.8e-05
      friction:
        symb: [1, 1]
        Dl: [0.1, 0.01]
    link2:
      inertial:
        symb: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
        mass: 0.0173
        CoM_x: 0.0
        CoM_y: 0.0
        CoM_z: 0.0
        Ixx: 1.52e-05
        Ixy: -2.09e-08
        Ixz: -9.8e-09
        Iyy: 1.3323e-05
        Iyz: -2.04e-06
        Izz: 2.85e-06
      friction:
        symb: [1, 1]
        Dl: [0.1, 0.01]
    link3:
      inertial:
        symb: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
        mass: 0.0367
        CoM_x: 0.0
        CoM_y: 0.0
        CoM_z: 0.0
        Ixx: 3.7e-06
        Ixy: 2.43e-07
        Ixz: 6.48e-07
        Iyy: 1.54e-05
        Iyz: -3.11e-08
        Izz: 1.388e-05
      friction:
        symb: [1, 1]
        Dl: [0.1, 0.01]
    link4:
      inertial:
        symb: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
        mass: 0.0348
        CoM_x: 0.0
        CoM_y: 0.0
        CoM_z: 0.0
        Ixx: 2.94e-06
        Ixy: 1.244e-07
        Ixz: 3.52e-07
        Iyy: 1.13e-05
        Iyz: -3.11e-08
        Izz: 1.06e-05
      friction:
        symb: [1, 1]
        Dl: [0.1, 0.01]

trajectory:
  type: 'ros2'
  bag: '/home/leo/Desktop/allegro_hand_ros2_ws/workdir/allegro_hand_thumb_2traject_bag'
  topic: '/allegroHand_0/joint_states'
  joints: ['joint_12_0', 'joint_13_0', 'joint_14_0', 'joint_15_0']  # Thumb joints

processing:
  cut_off_frequency: 30 # [rad/s]
  butterworth_order: 4
  decimate_factor: 10

identification:
  weight:
    loss: 1e6 # Error from Base Parameers
    norm: 0 # Parameters norm
    mass: 1e1
    CoM: 1e4
    inertia: 1e4
    link: [1,1,1,1]