version: 0.2
PI: &1 3.14163267948966
PI_2: &2 1.5707963267948966
PI_2_neg: -1.5707963267948966
num_joints: 4
type_joints: [R, R, R, R]
kinematics:
  symb: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
  DH: [0, 0, 0.017, *1, 0, *2, 0, *2, 0.0431, 0, 0, 0, 0.038, 0, 0, 0]
gravity:
  symb: [1, 1, 1]
  value: [0, 0, -9.81]
Base_to_L0:
  symb: [1, 1, 1, 1, 1, 1]
  tr: [0, -0.0009, 0]
  ypr: [0, 0, 0]
Ln_to_EE:
  symb: [1, 1, 1, 1, 1, 1]
  tr: [0.04, 0, 0]
  ypr: [0, 0, 0]
dynamics:
  link1:
    inertial:
      symb: [1,1,1,1,1,1,1,1,1,1]
      mass: 0.05930000049439022
      CoM_x: 2.5117617423621873e-20
      CoM_y: -5.21454845181994e-20
      CoM_z: 0.27500000049509316
      Ixx: 1.2854007999999612e-05
      Ixy: 2.04e-08
      Ixz: 1.89e-06
      Iyy: 1.224999999999924e-05
      Iyz: 1.51e-07
      Izz: 2.999e-06
      friction:
        symb: [1, 1]
        Dl: [0.1, 0.01]
  link2:
    inertial:
      symb: [1,1,1,1,1,1,1,1,1,1]
      mass: 0.053883647734288644
      CoM_x: 0.0016296062240333039
      CoM_y: 0.017410452272199013
      CoM_z: 0.024346125651936817
      Ixx: 1.8599189389857627e-05
      Ixy: 1.679982197143862e-06
      Ixz: -6.159299729140685e-06
      Iyy: 4.8698584571613365e-05
      Iyz: 3.509794053194816e-07
      Izz: 5.5699394134606255e-05
      friction:
        symb: [1, 1]
        Dl: [0.1, 0.01]
  link3:
    inertial:
      symb: [1,1,1,1,1,1,1,1,1,1]
      mass: 0.0010454900142708242
      CoM_x: -0.519346926037804
      CoM_y: 0.0009392707517486649
      CoM_z: 0.018429348308377374
      Ixx: 3.8099999724187234e-06
      Ixy: 5.720149456044377e-09
      Ixz: -9.970003449064721e-07
      Iyy: 1.4549994853825824e-05
      Iyz: 2.6299989937765135e-08
      Izz: 1.28999948726867e-05
      friction:
        symb: [1, 1]
        Dl: [0.1, 0.01]
  link4:
    inertial:
      symb: [1,1,1,1,1,1,1,1,1,1]
      mass: 0.003142732055517586
      CoM_x: 0.040236838569643725
      CoM_y: 0.5439128235893116
      CoM_z: -0.035635714667140134
      Ixx: 1.1699919180263151e-06
      Ixy: 5.0899466566062994e-09
      Ixz: -1.1842952621926735e-12
      Iyy: 2.399991760496825e-06
      Iyz: 3.632936372522863e-13
      Izz: 1.6699998097428502e-06
      friction:
        symb: [1, 1]
        Dl: [0.1, 0.01]