d3q: [0, 0, 0, 0, 0, 0, 0]
d4q: [0, 0, 0, 0, 0, 0, 0]
ddq: [0, 0, 0, 0, 0, 0, 0]
ddqr: [0, 0, 0, 0, 0, 0, 0]
dq: [0, 0, 0, 0, 0, 0, 0]
dqr: [0, 0, 0, 0, 0, 0, 0]
par_DYN: [0.735522, 0.010517, -0.004252, -0.045403, 0.012516, -0.000428, -0.001196, 0.010027, -0.000741, 0.004815]
par_REG: [0.735522, 0.007735484874, -0.0031274395439999996, -0.033394905366, 0.014045526761273585, -0.000395108718315752, -0.000844785780265778, 0.011624582982752355, -0.000882995137616232, 0.004909651967360946]
q: [0, 0, 0, 0, 0, 0, 0]
w: [0, 0, 0, 0, 0, 0]
